{
	"version": 1526306229,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/bird-sheet0.png",
		"images/tiledbackground.png",
		"images/tiledbackground2.png",
		"images/background-sheet0.png",
		"images/bottompipe-sheet0.png",
		"images/toppipe-sheet0.png",
		"images/sprite-sheet0.png",
		"images/cuts_0004_layer-sheet0.png",
		"images/cuts_0002_shootingstar-sheet0.png",
		"images/cuts_0001_layer-sheet0.png",
		"images/cuts_0010_layer-sheet0.png",
		"media/woosh.ogg",
		"media/star3.ogg",
		"media/background.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}